setwd("~/R")
z <- read.table("household_power_consumption.txt", sep = ";", header = TRUE,na.strings="?", stringsAsFactors=FALSE, dec=".")
o <- z[z$Date %in% c("1/2/2007","2/2/2007"),]
##str(o)
o[,1] <- as.Date(o[,1],format='%d/%m/%Y')
##class(z$Date)
o[,2] <- as.POSIXct(o[,2],format='%H:%M:%S')
##class(z$Time)
o[,2] <- strftime(o[,2], format='%H:%M:%S')
##combineddatetime <- strptime(paste(o$Date, o$Time, sep=" "), "%d/%m/%Y %H:%M:%S") 
o[,3] <- as.numeric(o[,3])
o[,4] <- as.numeric(o[,4])
o[,5] <- as.numeric(o[,5])
o[,6] <- as.numeric(o[,6])
o[,7] <- as.numeric(o[,7])
o[,8] <- as.numeric(o[,8])
##head(o)
o$combineddatetime<- as.POSIXct(paste(o$Date, o$Time))
png("plot2.png", width=480, height=480)
plot(o$Global_active_power~o$combineddatetime,ylab="Global Active Power (kilowatts)",xlab = "",type="l")
dev.off()
